ignore:
  - "test"                                                    # ignore test/ folder
  - "script"                                                  # ignore scripts/ folder
  - "lib"                                                     # ignore libs/ folder
  - "src/libraries"                                           # ignore src/libraries/ folder since coverage is not yet supported
  - "src/sample"                                              # ignore src/sample/ folder
  - "src/bridger/token-bridge-contracts/L2CustomGateway.sol"  # ignore L2CustomGateway.sol
  - "src/bridger/token-bridge-contracts/L2ERC20Gateway.sol"   # ignore L2ERC20Gateway.sol
  - "src/bridger/token-bridge-contracts/L2WethGateway.sol"    # ignore L2WethGateway.sol
  - "src/inflators/BundleBulker.sol"                          # ignore BundleBulker.sol

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false     # [true :: must have a base report to post]
  require_head: true      # [true :: must have a head report to post]